### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by doomkin** [lowenware/OS#2]
```
$ ./project.sh build
ld.lld -Tcore/core.ld build/core.o build/uart.o -o build/core.elf
objcopy --target elf64-littleaarch64 -O binary build/core.elf build/core.bin
objcopy:build/core.elf: Неверная цель bfd
make: *** [Makefile:25: build/core.bin] Ошибка 1
```

**Comment by Lowentwickler** [comment]
Какая версия objcopy?

**Comment by doomkin** [comment]
```
$ objcopy -V
GNU objcopy (GNU Binutils) 2.29.1
```

**Comment by Lowentwickler** [comment]
objcopy -h | grep targets 
должен содержать elf64-littleaarch64

Если этой цели в списке нет, значит binutils старый или просто собран без поддержки. Можно ещё поставить тулчейн для aarch64 и использовать binutils оттуда.

Если хочешь просто запустить проект, то уже сейчас можешь пробовать ./project.sh run, потому что core.elf собран.
Всё то, что делает binutils на данный момент частично не используется, а частично используется для отладки.

**Comment by doomkin** [comment]
```
$ ./project.sh run
1234567890ABCDEF
Starting Lowe OS
```
